"""init

Revision ID: 4dc89a3cd378
Revises: e827ac0cc2ab
Create Date: 2025-02-10 12:56:37.104384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc89a3cd378'
down_revision = 'e827ac0cc2ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('isFavorite', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isReading', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isFinished', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='book_pkey')
    )
    # ### end Alembic commands ###
