"""init

Revision ID: e827ac0cc2ab
Revises: 66c8948c6ddd
Create Date: 2025-02-10 12:46:10.518488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e827ac0cc2ab'
down_revision = '66c8948c6ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmaceutico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_farmaceutico', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paciente',
    sa.Column('hc', sa.String(length=255), nullable=False),
    sa.Column('nome_paciente', sa.String(length=255), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('sexo', postgresql.ENUM('Masculino', 'Feminino', 'Outro', name='sexo_enum'), nullable=False),
    sa.Column('endereco', sa.TEXT(), nullable=False),
    sa.Column('CRM_medico', sa.String(length=100), nullable=False),
    sa.Column('leito', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('hc')
    )
    op.create_table('prescricao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hc', sa.String(length=255), nullable=False),
    sa.Column('lista_remedios', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('aprovacao', sa.Boolean(), nullable=True),
    sa.Column('id_farmaceutico', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hc'], ['paciente.hc'], ),
    sa.ForeignKeyConstraint(['id_farmaceutico'], ['farmaceutico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescricao')
    op.drop_table('paciente')
    op.drop_table('farmaceutico')
    # ### end Alembic commands ###
